#!/bin/bash
 
# Adds client config to ccd folder for setting static IPs

CLIENT=$1
ADDRESS=$2

echo "ifconfig-push ${ADDRESS} 255.255.255.0" > conf/ccd/${CLIENT}
echo "Client ${CLIENT} given static IP ${ADDRESS}"