#!/bin/bash

# Copies required files to the /etc/openvpn directory for usage

SERVER=$1

sudo cp -r conf/ccd/ conf/${SERVER}.conf /etc/openvpn/server/

echo "Files copied to /etc/openvpn/server/

To start VPN server: sudo systemctl start openvpn-server@${SERVER}
To stop VPN server: sudo systemctl stop openvpn-server@${SERVER}"
