#!/bin/sh

# Copies client config to the /etc/openvpn/client directory for usage

CLIENT=$1

sudo cp conf/${CLIENT}.conf /etc/openvpn/client/

echo "Client config copied to /etc/openvpn/client/

To start VPN client: sudo systemctl start openvpn-client@${CLIENT}
To stop VPN client: sudo systemctl stop openvpn-client@${CLIENT}"
