#!/bin/sh

# Copies client config to the /etc/openvpn/client directory for usage

CLIENT=$1

sudo cp conf/${CLIENT}.conf /etc/openvpn/client/

echo "Client config copied to /etc/openvpn/client/

To start VPN client: sudo service openvpn@${CLIENT} start
To stop VPN client: sudo service openvpn@${CLIENT} stop"